[1주차 해바라기반]: 조현창 - 1541 잃어버린 괄호 Silver2(#2)
CBNU-Nnet/2022-algorithm-study pull request #3
Opened 2022-04-07 17:54 UTC by vcho1958

## 😀 PR을 올리기 전 준비
- [ ] assignee를 지정해주셨나요?
- [ ] reviewer(그룹원)를 지정해주셨나요?
- [ ] PR 제목 등 컨벤션을 확인하셨나요?

## 💡 소속 그룹
소속 그룹을 적어주세요.

## 🤩 이번주 문제

### 문제
세준이는 양수와 +, -, 그리고 괄호를 가지고 식을 만들었다. 그리고 나서 세준이는 괄호를 모두 지웠다.

그리고 나서 세준이는 괄호를 적절히 쳐서 이 식의 값을 최소로 만들려고 한다.

괄호를 적절히 쳐서 이 식의 값을 최소로 만드는 프로그램을 작성하시오.

### 입력
첫째 줄에 식이 주어진다. 식은 ‘0’~‘9’, ‘+’, 그리고 ‘-’만으로 이루어져 있고, 가장 처음과 마지막 문자는 숫자이다. 그리고 연속해서 두 개 이상의 연산자가 나타나지 않고, 5자리보다 많이 연속되는 숫자는 없다. 수는 0으로 시작할 수 있다. 입력으로 주어지는 식의 길이는 50보다 작거나 같다.

## 🧑‍💻 어떻게 푸셨나요?
최소가 되려면 양수인 부분을 모두 괄호로 묶으면 된다. 
따라서 수식의 특성상 수식의 -를 마주치기 전 모든 수를 sum변수에 더한 후에
-가 나오는 순간부터 있는 수들은 모두 빼는 변수 sub에 덧셈시키고
최종적으로 sum에서 sub를 빼서 결과값을 도출한다.
예시
1+2+3 => (1+2+3)
1-2+3-6 => 1-(2+3)-(6) 이처럼 - 이후는 +가 섞여있어도 결국 모두 뺴는 값에 포함된다.

```c++
#include <iostream>
#include <vector>
#include <deque>
#include <string>
using namespace std;

int main()
{
  ios_base::sync_with_stdio(0);
  cin.tie(NULL);
  cout.tie(NULL);
  string input;
  int a, res = 0, tmp = 0, minus = 0, sum = 0, sub = 0;
  vector<int> A;
  vector<char> op;

  cin >> input;
  for (int i = 0; i < input.length(); i++)
  {
    if (input[i] >= '0' && input[i] <= '9')
    {
      while (input[i] >= '0' && input[i] <= '9')
      {
        tmp *= 10;
        tmp += input[i] - '0';
        i++;
      }
    }
    A.push_back(tmp);
    tmp = 0;
    if (i < input.length())
      op.push_back(input[i]);
  }
  for (int i = 0; i < A.size(); i++)
  {
    if (minus)
    {
      sub += A[i];
    }
    else
    {
      res += A[i];
    }
    if (i < op.size())
    {
      if (op[i] == '-')
      {
        minus = 1;
      }
    }
  }
  cout << res - sub;
}
```
## ✍️ 질문을 적어주세요.
질문할 부분이 있으면 알려주세요.(선택사항)

## 📖 참고 사항
문제를 해결할 때 참고하셨던 것을 첨부해주세요.(선택사항)

2022-04-09 06:52 UTC, vcho1958 commented
```cpp
  for (int i = 0; i < input.length(); i++)
  {
    int tmp = 0;
    if (input[i] >= '0' && input[i] <= '9')
    {
      while (input[i] >= '0' && input[i] <= '9')
      {
        tmp *= 10;
        tmp += input[i] - '0';
        i++;
      }
    }
    res += tmp * sign;
    if (i < input.length() && input[i] == '-')
      sign = -1;
  }
  cout << res;
```
기존 방법은 배열에 먼저 숫자와 부호를 insert후 읽어서 하여 비효율적인 부분을
바로바로 반영하게하여 코드를 단축하고 효율성을 개선함

2022-04-09 07:29 UTC, sarah2234 commented on 해바라기반/조현창/1541잃어버린 괄호.cpp
> +  vector<int> A;
변수명이 (짧더라도) 좀 더 명확하면 좋겠습니다.

2022-04-09 07:31 UTC, sarah2234 commented on 해바라기반/조현창/1541잃어버린 괄호.cpp
> +  vector<int> A;
변수명이 (짧더라도) 좀 더 명확하면 좋겠습니다.

2022-04-09 07:35 UTC, vcho1958 commented on 해바라기반/조현창/1541잃어버린 괄호.cpp
> +  vector<int> A;
아하! 2번째 커밋에 반영했습니다!

2022-04-09 23:15 UTC, alirz-pixel commented
1주차 참여해 주셔서 감사드립니다. :)
적어주신 풀이 말고도 스택으로도 가능하니 시간 되실 때 도전해 보세요!

2022-04-09 23:16 UTC, alirz-pixel commented
그리고 PR title은[Collaboration Guide](https://github.com/CBNU-Nnet/2022-algorithm-study/issues/1)에 나와있는 것과 같이 `[{주차}] {그룹} - {이름}` 으로 적어주세요!

2022-04-09 23:17 UTC, alirz-pixel requested changes
PR title은[Collaboration Guide](https://github.com/CBNU-Nnet/2022-algorithm-study/issues/1)에 나와있는 것과 같이 `[{주차}] {그룹} - {이름}` 으로 적어주세요!

2022-04-10 00:41 UTC, alirz-pixel commented on 해바라기반/조현창/1541잃어버린 괄호 try2.cpp
> +      while (input[i] >= '0' && input[i] <= '9')
현창님이 작성하신 코드를 보다가 이 부분에서 `out of range`가 발생하지 않은 것을 보고 신기하여 좀 찾아보았습니다.
C++의 `string`의 경우, `string`의 length에 해당하는 index를 참조해도 exception을 발생않는다고 합니다.
[참고한 사이트](https://m.blog.naver.com/nimdrak/221982370058)

그래서 `visual studio 2019` 환경에서 문제가 발생할 만한 코드를 작성한 후에 디버깅을 해보았는데,
정말로 `string`의 length에 해당하는 index에 대해선 `out of range`가 발생하지 않더라고요.

덕분에 하나 알아갑니다.
![image](https://user-images.githubusercontent.com/74577714/162596247-51f56c6c-ce0c-42d0-b648-c34f0a96e250.png)
> 출력
> a
> abc

2022-04-10 00:46 UTC, alirz-pixel commented on 해바라기반/조현창/1541잃어버린 괄호 try2.cpp
> +      while (input[i] >= '0' && input[i] <= '9')
@sarah2234 님의 풀이(#4) 처럼 저도 한 글자마다 숫자를 parsing 했었는데, 
`while` 문으로 숫자를 parsing 하신 점이 굉장히 인상 깊었습니다.

2022-04-10 01:36 UTC, alirz-pixel approved these changes

2022-04-10 06:23 UTC, vcho1958 commented
@alirz-pixel 스택으로 풀어본 풀이도 추가했습니다!

2022-04-10 07:42 UTC, vcho1958 commented
로직은 이렇습니다.
1. 1글자씩 char 스택에 넣는다.
2. 모두 넣은 후 한개씩 팝시키면서 int로 형변환한 후 res에 더한다.
3. 만약 -를 마주치면 지금까지의 res를 sub변수에 대입하고 res를 0으로 초기화 시킨다.
4. 반복 후 스택이 비면 res-sub를 출력한다.

2022-04-10 10:24 UTC, alirz-pixel requested changes
재풀이에 대한 commit 메시지는
`[{주차} {반이름}] : {이름} - {번호 / 이름 / 티어} ({문제집issue번호}) - {추가내용}`
으로 작성 부탁드립니다.

2022-04-10 11:37 UTC, vcho1958 commented
> 재풀이에 대한 commit 메시지는 `[{주차} {반이름}] : {이름} - {번호 / 이름 / 티어} ({문제집issue번호}) - {추가내용}` 으로 작성 부탁드립니다.

넵

2022-04-10 13:55 UTC, alirz-pixel approved these changes

2022-04-10 13:57 UTC, alirz-pixel requested changes
요 커밋들도 [collaboration](https://github.com/CBNU-Nnet/2022-algorithm-study/issues/1) 맞춰서 수정해 주세요

![image](https://user-images.githubusercontent.com/74577714/162622341-b11a6d8b-1f26-4c5c-b0cb-4f922f6f1205.png)

2022-04-10 14:00 UTC, alirz-pixel approved these changes
다른 커밋이 올라온 상태에서 
수정해버리면 꼬여버리는군요 ㅎㅎ

다음부터는 컨벤션 잘 작성해서 올려주세요

2022-04-11 07:58 UTC, DongWooE approved these changes

2022-04-11 22:01 UTC, kingyong9169 approved these changes

2022-04-16 16:09 UTC, merged